<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Place Pending Order</name>
   <tag></tag>
   <elementGuidId>4f67bbd8-e408-4fe1-8c08-c7dcf07a819c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btnSubmit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btnSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f94ee53-159f-4395-bed7-4ac40cd53013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSubmit</value>
      <webElementGuid>0d300c3b-c91e-48cd-a3c3-f2c9244b3afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>order</value>
      <webElementGuid>f94b6922-8a61-4328-859d-4974c6dc619c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9531da89-b3f4-47bc-be72-348ae91ad49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>greenButton rounded10 pendingDivbutton colorWhite border-0 regularFont paddingButton submitPop  m-trade-live</value>
      <webElementGuid>341844f6-da44-42c6-a56f-947fbe502e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Place Pending Order</value>
      <webElementGuid>ec724384-2805-40a6-ae05-ac897eeaf359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tradeform&quot;)/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-5&quot;]/div[@class=&quot;row d-none d-lg-block&quot;]/div[@class=&quot;col-12 align-self-center colorDarkgrey semi-bold fontsize14&quot;]/div[@class=&quot;oneButton&quot;]/button[@class=&quot;greenButton rounded10 pendingDivbutton colorWhite border-0 regularFont paddingButton submitPop  m-trade-live&quot;]</value>
      <webElementGuid>e7a8955d-063b-4622-9c01-2d2d35ddb6d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btnSubmit']</value>
      <webElementGuid>0c63c090-6203-490e-bbd0-63a1761f7b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tradeform']/div/div/div[2]/div[9]/div/div/button</value>
      <webElementGuid>d7735962-65a3-4b3d-978e-07325bbda0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 0'])[2]/following::button[1]</value>
      <webElementGuid>926a5cf7-5578-4d8e-afa9-b1d2f9883bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimasi Loss'])[1]/following::button[1]</value>
      <webElementGuid>01a5346f-7694-4ea6-a974-c301b4c3f155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Place Pending Order'])[2]/preceding::button[1]</value>
      <webElementGuid>10b1ab82-d980-4903-ac64-399c26d6fdab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[2]/preceding::button[2]</value>
      <webElementGuid>8c40c71f-79fd-49c8-a734-833b4c06243e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Place Pending Order']/parent::*</value>
      <webElementGuid>205e7f2a-0d75-4ad3-b924-b4a3ddc96e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6bfaca9e-e224-4660-8aba-ebd293053a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'btnSubmit' and @type = 'submit' and (text() = 'Place Pending Order' or . = 'Place Pending Order')]</value>
      <webElementGuid>4f9fb06d-1b26-416a-ad51-07ccb8ac6ee6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
