<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ORDER SEKARANG</name>
   <tag></tag>
   <elementGuidId>ef60a063-efdc-4528-8648-b233835e4df9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btnSubmit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btnSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5257fd7c-ca3f-4ce7-8b6e-aa30d025772f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSubmit</value>
      <webElementGuid>12cec697-b2c5-489a-a2d8-70a208ca56f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>order</value>
      <webElementGuid>76f6ca28-502d-4ff1-a583-5da8c3a7b9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>eaf30bad-140a-497d-af4a-99803e2719de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>greenButton rounded10 pendingDivbutton colorWhite border-0 regularFont paddingButton submitPop  m-trade-live</value>
      <webElementGuid>9dc1c819-83aa-43b5-b00e-0e115d291e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ORDER SEKARANG</value>
      <webElementGuid>d995c46a-cc46-4fce-a9a8-0ca2f6f5f7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tradeform&quot;)/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-5&quot;]/div[@class=&quot;row d-none d-lg-block&quot;]/div[@class=&quot;col-12 align-self-center colorDarkgrey semi-bold fontsize14&quot;]/div[@class=&quot;oneButton&quot;]/button[@class=&quot;greenButton rounded10 pendingDivbutton colorWhite border-0 regularFont paddingButton submitPop  m-trade-live&quot;]</value>
      <webElementGuid>ba03b017-8692-49a6-9f0a-42f44a482274</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btnSubmit']</value>
      <webElementGuid>832bb4a6-a84d-4c8e-b8e7-2c8e45ffc0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tradeform']/div/div/div[2]/div[9]/div/div/button</value>
      <webElementGuid>f6d46202-3599-41ce-809a-c281ac8beded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 0'])[2]/following::button[1]</value>
      <webElementGuid>2a548f82-9faa-4dcb-825b-344b56931898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimasi Loss'])[1]/following::button[1]</value>
      <webElementGuid>87e23da4-f48c-4980-a040-860d5d2e1bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORDER SEKARANG'])[2]/preceding::button[1]</value>
      <webElementGuid>6cddf6e3-afbe-4374-acde-630805dc73fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[2]/preceding::button[2]</value>
      <webElementGuid>7782dc5d-f4a1-4dee-b86d-f7b8b448767b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ORDER SEKARANG']/parent::*</value>
      <webElementGuid>5e98210e-0a71-4156-b771-473c94049429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>665cea8b-09e6-47d9-9eda-070a8ccf284b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'btnSubmit' and @type = 'submit' and (text() = 'ORDER SEKARANG' or . = 'ORDER SEKARANG')]</value>
      <webElementGuid>e05d6c21-b05b-42fd-8588-d189d3880277</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
