<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sell</name>
   <tag></tag>
   <elementGuidId>aee1eea5-7370-412e-ad78-2526d7795e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#direction-sell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='direction-sell']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>41dceec5-e778-4357-b2aa-1ad29134f0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>direction-sell</value>
      <webElementGuid>ef2c60e5-4a9c-40a7-9ad0-6a0c1f5c2ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> directionDefault divArrowsell pointer defaultBorderRadius regularFont semi-bold text-left</value>
      <webElementGuid>079a5adf-3a2a-4008-aa84-af60592e0a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sell</value>
      <webElementGuid>562e5f8c-c01c-4271-a74a-db5b5036c8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;direction-sell&quot;)</value>
      <webElementGuid>3ce83307-a129-4ac7-af1e-217721436f47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='direction-sell']</value>
      <webElementGuid>0ee35228-d3b9-4b71-adf3-27fe78b58bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tradeform']/div/div/div[2]/div/div[3]/div[2]/div</value>
      <webElementGuid>bccfb562-1898-4f06-a996-103ab6e1b963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy'])[1]/following::div[2]</value>
      <webElementGuid>1ae07256-8df5-4ee4-a4da-e71a01836057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direction'])[1]/following::div[6]</value>
      <webElementGuid>f60f3b59-9af5-4eb3-8811-617a379f76c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/preceding::div[2]</value>
      <webElementGuid>a820492d-ae75-45eb-80c3-cf8751874ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div[2]/div</value>
      <webElementGuid>7d5b257e-029f-4c3c-bd5a-3a2f26836f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'direction-sell' and (text() = ' Sell' or . = ' Sell')]</value>
      <webElementGuid>46e82121-0054-4023-bc27-6a4b15dac965</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
