<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Harga Entry_price_limit</name>
   <tag></tag>
   <elementGuidId>dfbca580-9558-4795-84ca-40ba63735b85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#price_limit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='price_limit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e95711e-9491-425e-8d51-e7fa7544e6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pendingAttr colorBlack border-0 text-center</value>
      <webElementGuid>8444096b-074a-4152-babf-b01f4dfc2a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>price_limit</value>
      <webElementGuid>bd1fcfbe-1e6f-4fc9-98c0-b4975554a859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>price_limit</value>
      <webElementGuid>a758d49d-37a2-4522-8123-140f80ab4c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6975c0cf-e522-499d-9f69-80b8b1015b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;price_limit&quot;)</value>
      <webElementGuid>b5f53e7c-b133-473d-a9f0-92078e35cc6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='price_limit']</value>
      <webElementGuid>60f8150a-3a78-4f11-a8dd-99182b7d8feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tradeform']/div/div/div[2]/div[3]/div[2]/div[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>886e6672-da59-4932-ad82-035a313a2258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>4144c974-7e9b-4ec4-8250-0cbe751b754a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'price_limit' and @name = 'price_limit' and @type = 'text']</value>
      <webElementGuid>da17946a-c4f7-4c54-995f-45fa100f5566</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
