<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_LiveTmp_password</name>
   <tag></tag>
   <elementGuidId>ab4d2f74-328d-402c-b375-393d44698d6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LiveTmp_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LiveTmp_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce6f74d4-fab9-4f17-a558-bbf265cdf7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>337b755b-3da7-42ab-ae02-fdfad3263c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LiveTmp_password</value>
      <webElementGuid>1b768e3b-9ae6-4765-8056-a95bcc758386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9d4ec76f-61e8-484f-8e2f-14c632d1091b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>defaultcss rounded4 pswdtext</value>
      <webElementGuid>03672007-96b4-4444-ad4b-d06faaf61730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LiveTmp_password&quot;)</value>
      <webElementGuid>3a6057ef-4ecf-416c-b60a-8fe6fc8e3c03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LiveTmp_password']</value>
      <webElementGuid>08d7e5d5-5943-4d81-9064-39fddf57c31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>7bb9c5c3-9669-47c9-ab40-11c0929e72da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @id = 'LiveTmp_password' and @type = 'password']</value>
      <webElementGuid>73c27ee0-ceb1-42b6-9cad-778193ff91b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
